Nome=input("Digite seu nome: ")
print("Bem vindo",Nome)
n1=input("Digite um número: ")
n2=input("Digite um número: ")
Soma= int(n1)+int(n2)
Subtração= int(n1)-int(n2)
Multiplicação= int(n1)*int(n2)
Divisão= int(n1)/int(n2)
print(Soma)